# Generated by Django 6.0 on 2025-12-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('country', models.CharField(max_length=100, verbose_name='国家')),
                ('description_en', models.TextField(verbose_name='英文描述')),
                ('description_zh', models.TextField(blank=True, verbose_name='中文描述')),
                ('content', models.TextField(verbose_name='详细内容')),
                ('category', models.CharField(max_length=50, verbose_name='类型')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '世界遗产',
                'verbose_name_plural': '世界遗产',
                'db_table': 'heritage_site',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('full', '全量爬取'), ('single', '单条更新')], max_length=20, verbose_name='任务类型')),
                ('target_url', models.URLField(blank=True, null=True, verbose_name='目标URL')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_items', models.IntegerField(default=0, verbose_name='总条目数')),
                ('processed_items', models.IntegerField(default=0, verbose_name='已处理数')),
                ('current_item', models.CharField(blank=True, max_length=255, verbose_name='当前处理项')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '爬取任务',
                'verbose_name_plural': '爬取任务',
                'db_table': 'crawl_task',
                'ordering': ['-started_at'],
            },
        ),
    ]
