# Generated by Django 6.0 on 2025-12-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawltask',
            name='current_item_progress',
            field=models.IntegerField(default=0, verbose_name='当前项进度'),
        ),
    ]
